lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list, friend_detail


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-friend/$', add_friend, name='add-friend'),
    url(r'^validate-npm/$', validate_npm, name='validate-npm'),
    url(r'^delete-friend/(?P<friend_id>[0-9]+)/$', delete_friend, name='delete-friend'),
    url(r'^get-friend-list/$', friend_list, name='get-friend-list'),
    url(r'^friend-detail/(?P<friend_id>[0-9]+)/$', friend_detail, name='friend-detail'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include('lab_1.urls', namespace='lab-1')),
    url(r'^lab-2/', include('lab_2.urls', namespace='lab-2')),
    url(r'^lab-2-addon/', include('lab_2_addon.urls', namespace='lab-2-addon')),
    url(r'^lab-3/', include('lab_3.urls', namespace='lab-3')),
    url(r'^lab-4/', include('lab_4.urls', namespace='lab-4')),
    url(r'^lab-5/', include('lab_5.urls', namespace='lab-5')),
    url(r'^lab-6/', include('lab_6.urls', namespace='lab-6')),
    url(r'^lab-7/', include('lab_7.urls', namespace='lab-7')),
    url(r'^lab-9/', include('lab_9.urls', namespace='lab-9')),
    url(r'^$', RedirectView.as_view(url='/lab-4/', permanent=True), name='index')
]

lab_7/models.py
from __future__ import unicode_literals
from django.db import models


class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250, unique=True)
    added_at = models.DateField(auto_now_add=True)

    def as_dict(self):
        return {
            'id': self.id,
            'friend_name': self.friend_name,
            'npm': self.npm,
        }

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os


response = {}
csui_helper = CSUIhelper()


def index(request):
    mahasiswa_list = csui_helper.instance.get_mahasiswa_list()
    friend_list = Friend.objects.all()
    response['mahasiswa_list'] = mahasiswa_list
    response['friend_list'] = friend_list
    html = 'lab_7/lab_7.html'
    return render(request, html, response)


def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar_teman.html'

    if request.is_ajax():
        friend_list = [obj.as_dict() for obj in friend_list]
        return JsonResponse({'friends': friend_list}, content_type='application/json')

    return render(request, html, response)


def friend_detail(request, friend_id):
    mahasiswa_list = csui_helper.instance.get_mahasiswa_list()
    html = 'lab_7/detail_teman.html'
    mahasiswa = None
    for data in mahasiswa_list:
        if data['nama'] == Friend.objects.get(id=friend_id).friend_name:
            mahasiswa = data
            break

    if mahasiswa is not None:
        response['nama'] = mahasiswa['nama'].title()
        response['tgl_lahir'] = mahasiswa['tgl_lahir']
        response['alamat_mhs'] = mahasiswa['alamat_mhs']
        response['jurusan'] = mahasiswa['program'][0]['nm_org']
        return render(request, html, response)
    else:
        return HttpResponse("Data tidak ditemukan.")


'''def friend_list_json(request):
    friends = [obj.as_dict() for obj in Friend.objects.all()]
    return JsonResponse({'results': friends}, content_type='application/json')'''


@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        friend = Friend(friend_name=name, npm=npm)
        friend.save()
        return JsonResponse(friend.as_dict())


def delete_friend(request, friend_id):
    Friend.objects.filter(id=friend_id).delete()
    return HttpResponseRedirect('/lab-7/')


@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    data = {
        'is_taken': Friend.objects.filter(npm=npm).exists()
    }
    return JsonResponse(data)

lab_7/templates/lab_7/daftar_teman.html
{% extends 'lab_7/layout/base.html' %}

{% block content %}
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2>Teman-Teman Fasilkom</h2>
                    <div id="my-friends" class="list-group">

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block Javascript %}
    <script>
        $(document).ready(function() {
            $.ajax({
                method: 'GET',
                url: "{% url 'lab-7:get-friend-list' %}",
                success: function(response) {
                    var friends = response['friends'];
                    friends.forEach(function(friend) {
                        var friendID = friend.id;
                        $('#my-friends').append(
                            '<a class="list-group-item clearfix" ' +
                            'href="{% url 'lab-7:friend-detail' friend_id=1234 %}" target="_blank">'.replace(/1234/, friendID) +
                              friend.friend_name + '</a>');

                        /*.append(
                                  '<button class=delete-button ' + 'id='
                            + friendID + '>Hapus Teman</button>');*/
                    });
                },
                error: function(error) {
                    alert(error.responseText);
                }
            });

            /*$('#my-friends').on('click', '.delete-button', function() {
                var id = $(this).attr('id');
                var url = "{% url 'lab-7:delete-friend' friend_id=1234 %}".replace(/1234/, id);
                $.ajax({
                    method: 'GET',
                    url: url,
                    success: function(data) {
                        $('#my-friends').html(data);
                    },
                    error: function(error) {
                        alert(error.responseText);
                    }
                });
            });*/

        });
    </script>
{% endblock %}

lab_7/templates/lab_7/detail_teman.html
{% extends 'lab_7/layout/base.html' %}

{% block content %}
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2>Data {{ nama }}</h2>
                    <div id="my-friends" class="list-group">
                        Tanggal Lahir: {{ tgl_lahir }}<br>
                        Alamat: {{ alamat_mhs }}<br>
                        Jurusan: {{ jurusan }}<br>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends 'lab_7/layout/base.html' %}
{% block content %}
    <section name="mahasiswa-list" id="mahasiswa-list">
        <div content="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2>Mahasiswa Fasilkom</h2>
                    <div class="list-group">
                        {% if mahasiswa_list %}
                            {% for mahasiswa in mahasiswa_list %}
                                <a class="list-group-item clearfix">
                                    {{ mahasiswa.name }} {{ mahasiswa.npm }}
                                    <span class="pull-right">
                                        <span class="btn btn-xs btn-default"
                                              onclick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                                            Tambah sebagai teman
                                        </span>
                                    </span>
                                </a>
                            {% endfor %}
                        {% else %}
                            <div class="alert alert-danger text-center">
                                <strong>Oops!</strong> Tidak ada mahasiswa
                            </div>
                        {% endif %}
                    </div>
                </div>

                <div class="col-lg-4">
                    <h2>Teman Saya</h2>
                    <div class="list-group" id="friend-list">
                        {% if friend_list %}
                            {% for friend in friend_list %}
                                <a class="list-group-item clearfix">
                                    {{ friend.friend_name }}
                                </a>
                            {% endfor %}
                        {% else %}
                            <div class="alert alert-danger text-center">
                                <strong>Oops!</strong> Tidak ada teman
                            </div>
                        {% endif %}
                    </div>

                    <form id="add-friend" action="#">
                        {% csrf_token %}
                        <label for="field_npm">NPM</label>
                        <input id="field_npm" type="text" name="npm" class="form-control">
                        <label for="field_name">Nama</label>
                        <input id="field_name" type="text" name="name" class="form-control">
                        <button type="submit">Tambah</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

    {% block Javascript %}
        <script>
            var addFriend = function(nama, npm) {
              $.ajax({
                  method: "POST",
                  url: "{% url 'lab-7:add-friend' %}",
                  data: {name: nama, npm: npm},
                  success: function(friend) {
                      html = '<a class="list-group-item clearfix">' +
                              friend.friend_name + '</a>';
                      $('#friend-list').append(html);
                  },
                  error: function(error) {
                      alert("Teman sudah ditambah.");
                  }
              });
            };

            $('#add-friend').on("submit", function() {
               var name = $('#field_name').val();
               var npm = $('#field_npm').val();
               addFriend(name, npm);
               event.preventDefault();
            });

            $('#field_npm').change(function() {
               console.log($(this).val());
               var npm =  $(this).val();
               $.ajax({
                   method: "POST",
                   url: '{% url 'lab-7:validate-npm' %}',
                   data: {
                       npm: npm
                   },
                   dataType: 'json',
                   success: function(data) {
                       console.log(data);
                       if (data.is_taken) {
                           alert('Mahasiswa dengan npm seperti ini sudah ada');
                       }
                   }
               });
            });

        </script>
    {% endblock %}
{% endblock %}